language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.4
  - 2.3

gemfile:
  - Gemfile

before_script:
  - "echo 'Deprecated!!!! These are not exhaustive'"

script:
  - "bundle exec rspec spec/lib/quandl/client/base_spec.rb"
